version: 1.0.{build}

branches:
  only:
    - master

max_jobs: 1
image: Visual Studio 2017
clone_folder: C:\QDiscord
shallow_clone: false
clone_depth: 5

install:
  - mkdir tmp bin
  - git submodule update --init
  - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem
  - ps: Invoke-WebRequest -OutFile C:\Manticore\tmp\premake5.zip https://github.com/premake/premake-core/releases/download/v5.0.0-alpha12/premake-5.0.0-alpha12-windows.zip
  - ps: ([System.IO.Compression.ZipFile]::ExtractToDirectory('C:\QDiscord\tmp\premake5.zip', 'C:\QDiscord\bin\'))
  - cmd: cd C:\QDiscord\src & call ..\bin\premake5.exe --file=premake/main.lua vs2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

build:
  parallel: true
  project: src\QDiscord.sln
